### ISSUE TITLE
Moving from gitter to something else e.g. discord ...

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/forum#13]
Gitter does not seem to be getting a lot of love and personally i find it slow and buggy (e.g. image pasting) and increasingly found i don't open it for days at a time.

I therefore wanted to propose moving to a different chat system.

**Comment by roll** [comment]
Anything should be better than Gitter.. Just a few options:

- Slack - https://slack.com/intl/en-ru/
- Discord - https://discordapp.com/
- Spectrum - https://spectrum.chat/

**Comment by rufuspollock** [comment]
I'm 👎 on slack b/c of limited message history w/o paid (and we can't pay for community as many members).

Discord: quite like the feel. I'm currently trialling discord and quite like it and gets quite a bit of use in dev community esp JS and pretty full featured. So 👍 

Spectrum would be a 👍  for open source. But i'm not sure of their trajectory post github acquisition - i suspect github are going to shutter that product in favour of github discussions once integrated.

=> discord is my current default recommendation. Happy to have thoughts.

**Comment by lwinfree** [comment]
sounds good to me! As long as we can still have easy (& quick) chat function, I don't have a strong opinion.

**Comment by rufuspollock** [comment]
We're trialling a new discord channel here: https://discord.gg/2UgfM2k

**Comment by johanricher** [comment]
For what it's worth, we've been using [Riot](https://riot.im) (Matrix protocol) for 3 years and we're quite happy with it. The [new Android app](https://play.google.com/store/apps/details?id=im.vector.riotx&hl=en) is also very good.
These days it's [very easy to deploy ](https://youtu.be/dDddKmdLEdg) but [service plans](https://modular.im/services/matrix-hosting) also exist.

I'm not sure I would trust Discord with my enterprise data...

**Comment by rufuspollock** [comment]
@johanricher for community project with potentially many users i can't really have per user pricing and i'm not going to self host so riot seems out.

**Comment by johanricher** [comment]
For the record, only users with an account created on your matrix homeserver would be counted on the Modular.im plan (so you could just limit that to the core FD team). Since Matrix is an interoperable protocol, users from another homeserver (matrix.org or our own matrix.jailbreak.paris for example) could still join a room on your server and talk with all users in that room.

It's a bit like email, with an email account on a specific server but you can still exchange messages with other email servers.

But I understand that simplicity is key here and that's not where open protocols and open source projects shine!

**Comment by rufuspollock** [comment]
@johanricher right but that doesn't solve the issue for people who don't happen to be running on a matrix compatible system 😉 And as per a phrase I coined at Open Knowledge we're "pragmatic not fanatic" about open stuff ...

**Comment by johanricher** [comment]
>  issue for people who don't happen to be running on a matrix compatible system

That issue comes with any choice. Regardless of the system you end up choosing, they will have to join it, create an account, etc.

Creating and using an account on the matrix.org server is free, as would be creating and using rooms on the main matrix.org server with a matrix.org user account. You could also use the main [Riot](https://riot.im/app/) client, also for free. Any user from any server could join your rooms and chat as you would expect.

What I explained above is the way to get a custom server. Just wanted to clarify that point.

**Comment by johanricher** [comment]
But if the SaaS + free criteria is not negotiable there's no point to discuss it further. Sorry about derailing the discussion!

**Comment by rufuspollock** [comment]
@johanricher you didn't derail - these were really useful points and it's allowed me to revisit riot / modular (i last looked a couple of years ago). They seem really interesting but may not be a great fit for our use case of a community chat room (vs e.g. a chat room for a team) ... but maybe they are which brings to me:

Perhaps you could clarify for me: can we create rooms on matrix.org for free? If so that changes things - since it is a) SaaS b) free => we could use it. (I couldn't see on matrix.org where to sign up ...).

**Comment by johanricher** [comment]
Short answer: yes you can! :)

Note: "Matrix" is the name of the protocol and "matrix.org" the main Matrix server instance . "Riot" (riot-web, riotX-android, riot-ios) is the most popular Matrix client, and the official web instance is at [Riot.im/app](https://riot.im/app).

Here's the link to create a Matrix account on matrix.org: https://riot.im/app/#/register

That will give you an account ("@username:matrix.org" ; mine is [@johan:jailbreak.paris](https://matrix.to/#/@johan:jailbreak.paris)). Once connected you can create rooms on the matrix.org server ("#room:matrix.org"). You can also join other rooms on that server or even in other servers (for example: [#general:jailbreak.paris]( https://matrix.to/#/!general:jailbreak.paris)).

**Comment by iamraf-ca** [comment]
@rufuspollock, there are two questions on [Gitter](https://gitter.im/datahubio/chat) about the COVID-19 dataset and no one from Datopian to answer.

If the migration to Discord is already approved moving forward, we should close the Gitter chat or pin a message redirecting to the Datopian public room on Discord. What do you think?

**Comment by iamraf-ca** [comment]
I've also opened an issue on [Carbon Dooms Day](https://github.com/datopian/carbondoomsday/issues/15) to change the link from Gitter to Discord.

We need to find all links that point to Gitter on Datopian dashboards/repositories and change it to Discord.

**Comment by rufuspollock** [comment]
@toguko datahub.io channel is separated from Frictionless - see https://github.com/datopian/datahub-qa/issues/258 (/cc @sglavoie )

**Comment by rufuspollock** [comment]
FIXED. I think we are going with discord for now.

**Comment by augusto-herrmann** [comment]
I just learned now about this thread and the move from Gitter to Discord.

I oppose using Discord because:

1. It's closed and proprietary; and
2. most importantly, it has bad terms of service and privacy practices.

I know that no one reads those, but you can read a summary highlighting the bad points at [the Discord entry on TOSDR.org](https://tosdr.org/#discord).

On the other hand, I have read the matrix.org server terms of service (I always do when I sign up for a service, and being too long is one reason I use often to give up using a service) and they seem acceptable to me.

Another open source alternative that does fit the criteria (SaaS + free) is [Mumble](https://www.mumble.info/). [Mumble.com](https://www.mumble.com/) offers paid hosting for Mumble, but there is a list of free Mumble servers on [Chatons](https://chatons.org/en).

**Comment by rufuspollock** [comment]
@augusto-herrmann the deal-breakers for matrix was a free server (or, at least one that i could work out how to use or others to easily join).

For our purposes, 0-costness, usability and esp ease of use and potential network size trump open or not considerations. I'd have really like to continue using gitter but it seems to see very little maintenance from gitlab since acquisition.

Happy to hear other's priorities and options - i'd love to have an open source solution that met the criteria.

**Comment by augusto-herrmann** [comment]
@rufuspollock matrix does have a free server that is easy for people to sign up to. As @johanricher [mentioned above](https://github.com/frictionlessdata/forum/issues/13#issuecomment-612605112) and even posted the link:

> Here's the link to create a Matrix account on matrix.org: https://riot.im/app/#/register
> 
> That will give you an account ("@username:matrix.org" ; mine is [@johan:jailbreak.paris](https://matrix.to/#/@johan:jailbreak.paris)). Once connected you can create rooms on the matrix.org server ("#room:matrix.org"). You can also join other rooms on that server or even in other servers (for example: [#general:jailbreak.paris](https://matrix.to/#/!general:jailbreak.paris)).

I myself do have an account at that server and it was easy for me to set up.

Another option is [Mumble](https://www.mumble.info/), although I have yet to use it. As I mentioned, [Chatons](https://chatons.org/) maintains a list of free servers that people can sign up to:

https://wiki.chatons.org/doku.php/la_conference_telephonique_avec_mumble#instances_publiques_deployees

**Comment by rufuspollock** [comment]
@augusto-herrmann yes and i spent about 30m trying out  the matrix option. I found it difficult and also was not clear how we got our own space without creating our own server  e.g. i could create a channel (which i did https://riot.im/app/#/room/#frictionless:matrix.org) but how did i share it ...? This was the page i landed on and i was lost ...

![image](https://user-images.githubusercontent.com/180658/83531194-ef2a8600-a4ec-11ea-91b7-a9c0c7c70822.png)

Over the years of working in the open space I've emphasized pragmatic not fanatic. I used skype, I use zoom etc. I'm a strong advocate of open *and* in this case these things are tools and my focus is on the tool working really well and it seemed discord was best fit as UX seemed excellent, unlimited users, easy to join etc.

> Another option is Mumble, although I have yet to use it. As I mentioned, Chatons maintains a list of free servers that people can sign up to:

And that's the point: you haven't  used it, i haven't used it, most people haven't  used it so another hurdle for people 😉

**Comment by augusto-herrmann** [comment]
How do you share it? Like you just did. I have followed your link to the frictionless chat room and joined, easy peasy. :slightly_smiling_face: 

The screen you found confusing is only asking you to pick a Matrix client. If you're using Riot.im like I am, just click the corresponding link and you're done.

Skype ceased to be secure long ago, and Zoom is a security disaster. I only use it because I have no other option, as there are activities I took part on before the pandemic that moved in to Zoom when they started being remote. Even then, I only use it inside a Virtual Machine to contain possible security breaches.

> >  Another option is Mumble, although I have yet to use it. As I mentioned, Chatons maintains a list of free servers that people can sign up to:
> And that's the point: you haven't used it, i haven't used it, most people haven't used it so another hurdle for people wink

The only reason I haven't used Mumble yet is because I haven't needed it so far. But I am not opposed to start using it. On the other hand, I have never used Discord before and don't intend to start using it because I **disagree with its terms of service**, especially the account termination provision and shady user tracking practices.

![Screenshot_2020-06-02 Terms of Service; Didn't Read](https://user-images.githubusercontent.com/1058414/83537044-6c90cf00-a4ca-11ea-81cb-53387089c8ae.png)

**Comment by rufuspollock** [comment]
@augusto-herrmann i think you are somewhat unusual relatively re security and privacy concerns on these items 😄 (e.g. lots of people use zoom w/o great concerns).  I do hear you, just that most people don't necessarily have that concern. Also i emphasize many substantial tech communities are on discord etc.

If you are up for doing a detailed UX breakdown of say riot vs discord I'm happy to support you. I'd start with key criteria e.g. new joiner, existing network (people use a limited number of chat apps) etc.

**Comment by augusto-herrmann** [comment]
I know that:

1. the decision has already been made and you have already moved (part of) the community from Gitter to Discord; and
2. I and possible other people aren't joining Discord unless they change to a more user friendly [terms of service](https://tosdr.org/#discord) (even Slack has much better terms of service than Discord),

but I found it interesting to note that [Gitter has since joined Element](https://element.io/blog/gitter-is-joining-element/).

**Comment by lwinfree** [comment]
thanks @augusto-herrmann. I just started using element for something else & it seems pretty good. Maybe we can revisit this in April 2021 so we'll have had a year using Discord. There are several things that I personally don't love about Discord, but I could probably complain about every messaging app ;-)

**Comment by augusto-herrmann** [comment]
Thanks.

I've seen communities use both Discord and Element, linked by an automated bridge. People can communicate seamlessly on either app. Perhaps this could work out for the Frictionless community as well.
